# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-11 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inviteuser', '0003_auto_20160611_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
