# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-11 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inviteuser', '0004_invite_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inviteduser',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='inviteduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='InvitedUser',
        ),
    ]
